# postgres-service.yaml: Define um Service para o banco de dados PostgreSQL.
apiVersion: v1
kind: Service
metadata:
  name: postgres-service   # Nome do Service
spec:
  selector:
    app: postgres   # Seleciona os PODs que correspondem a este rótulo
  ports:
  - port: 5432   # Porta em que o Service estará escutando
    targetPort: 5432   # Porta em que o PostgreSQL está escutando dentro dos PODs
