global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "contador-vendas"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: ["contador-vendas-service:8080"]
