apiVersion: apps/v1
kind: Deployment
metadata:
  name: contador-vendas
spec:
  replicas: 4
  selector:
    matchLabels:
      app: contador-vendas
  template:
    metadata:
      labels:
        app: contador-vendas
    spec:
      containers:
      - name: contador-vendas
        image: alfecjo/ic-devops:1.0
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 10
          failureThreshold: 1